name = "worker"
main = "./src/index.ts"
compatibility_date = "2022-09-08"

[durable_objects]
bindings = [{name = "Y_DOCUMENT", class_name = "YDocument"}]

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["Counter"]

[[migrations]]
tag = "v2"
new_classes = ["YDocument"]
deleted_classes = ["Counter"] # Array of deleted class names